/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package IdentificationDatabase.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AddressLookup service. Represents a row in the &quot;ID_AddressLookup&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link IdentificationDatabase.model.impl.AddressLookupModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link IdentificationDatabase.model.impl.AddressLookupImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AddressLookup
 * @see IdentificationDatabase.model.impl.AddressLookupImpl
 * @see IdentificationDatabase.model.impl.AddressLookupModelImpl
 * @generated
 */
@ProviderType
public interface AddressLookupModel extends BaseModel<AddressLookup>,
	GroupedModel, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a address lookup model instance should use the {@link AddressLookup} interface instead.
	 */

	/**
	 * Returns the primary key of this address lookup.
	 *
	 * @return the primary key of this address lookup
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this address lookup.
	 *
	 * @param primaryKey the primary key of this address lookup
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this address lookup.
	 *
	 * @return the ID of this address lookup
	 */
	public long getId();

	/**
	 * Sets the ID of this address lookup.
	 *
	 * @param id the ID of this address lookup
	 */
	public void setId(long id);

	/**
	 * Returns the group ID of this address lookup.
	 *
	 * @return the group ID of this address lookup
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this address lookup.
	 *
	 * @param groupId the group ID of this address lookup
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this address lookup.
	 *
	 * @return the company ID of this address lookup
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this address lookup.
	 *
	 * @param companyId the company ID of this address lookup
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this address lookup.
	 *
	 * @return the user ID of this address lookup
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this address lookup.
	 *
	 * @param userId the user ID of this address lookup
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this address lookup.
	 *
	 * @return the user uuid of this address lookup
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this address lookup.
	 *
	 * @param userUuid the user uuid of this address lookup
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this address lookup.
	 *
	 * @return the user name of this address lookup
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this address lookup.
	 *
	 * @param userName the user name of this address lookup
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this address lookup.
	 *
	 * @return the create date of this address lookup
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this address lookup.
	 *
	 * @param createDate the create date of this address lookup
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this address lookup.
	 *
	 * @return the modified date of this address lookup
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this address lookup.
	 *
	 * @param modifiedDate the modified date of this address lookup
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the code of this address lookup.
	 *
	 * @return the code of this address lookup
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this address lookup.
	 *
	 * @param code the code of this address lookup
	 */
	public void setCode(String code);

	/**
	 * Returns the organization ID of this address lookup.
	 *
	 * @return the organization ID of this address lookup
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this address lookup.
	 *
	 * @param organizationId the organization ID of this address lookup
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the parent ID of this address lookup.
	 *
	 * @return the parent ID of this address lookup
	 */
	public long getParentId();

	/**
	 * Sets the parent ID of this address lookup.
	 *
	 * @param parentId the parent ID of this address lookup
	 */
	public void setParentId(long parentId);

	/**
	 * Returns the name of this address lookup.
	 *
	 * @return the name of this address lookup
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this address lookup.
	 *
	 * @param name the name of this address lookup
	 */
	public void setName(String name);

	/**
	 * Returns the level of this address lookup.
	 *
	 * @return the level of this address lookup
	 */
	@AutoEscape
	public String getLevel();

	/**
	 * Sets the level of this address lookup.
	 *
	 * @param level the level of this address lookup
	 */
	public void setLevel(String level);

	/**
	 * Returns the description of this address lookup.
	 *
	 * @return the description of this address lookup
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this address lookup.
	 *
	 * @param description the description of this address lookup
	 */
	public void setDescription(String description);

	/**
	 * Returns the status of this address lookup.
	 *
	 * @return the status of this address lookup
	 */
	public int getStatus();

	/**
	 * Sets the status of this address lookup.
	 *
	 * @param status the status of this address lookup
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		IdentificationDatabase.model.AddressLookup addressLookup);

	@Override
	public int hashCode();

	@Override
	public CacheModel<IdentificationDatabase.model.AddressLookup> toCacheModel();

	@Override
	public IdentificationDatabase.model.AddressLookup toEscapedModel();

	@Override
	public IdentificationDatabase.model.AddressLookup toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}