/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package IdentificationDatabase.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.sql.Blob;

import java.util.Date;

/**
 * The base model interface for the BiometricData service. Represents a row in the &quot;ID_BiometricData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link IdentificationDatabase.model.impl.BiometricDataModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link IdentificationDatabase.model.impl.BiometricDataImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BiometricData
 * @see IdentificationDatabase.model.impl.BiometricDataImpl
 * @see IdentificationDatabase.model.impl.BiometricDataModelImpl
 * @generated
 */
@ProviderType
public interface BiometricDataModel extends BaseModel<BiometricData>,
	GroupedModel, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a biometric data model instance should use the {@link BiometricData} interface instead.
	 */

	/**
	 * Returns the primary key of this biometric data.
	 *
	 * @return the primary key of this biometric data
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this biometric data.
	 *
	 * @param primaryKey the primary key of this biometric data
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this biometric data.
	 *
	 * @return the ID of this biometric data
	 */
	public long getId();

	/**
	 * Sets the ID of this biometric data.
	 *
	 * @param id the ID of this biometric data
	 */
	public void setId(long id);

	/**
	 * Returns the group ID of this biometric data.
	 *
	 * @return the group ID of this biometric data
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this biometric data.
	 *
	 * @param groupId the group ID of this biometric data
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this biometric data.
	 *
	 * @return the company ID of this biometric data
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this biometric data.
	 *
	 * @param companyId the company ID of this biometric data
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this biometric data.
	 *
	 * @return the user ID of this biometric data
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this biometric data.
	 *
	 * @param userId the user ID of this biometric data
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this biometric data.
	 *
	 * @return the user uuid of this biometric data
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this biometric data.
	 *
	 * @param userUuid the user uuid of this biometric data
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this biometric data.
	 *
	 * @return the user name of this biometric data
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this biometric data.
	 *
	 * @param userName the user name of this biometric data
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this biometric data.
	 *
	 * @return the create date of this biometric data
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this biometric data.
	 *
	 * @param createDate the create date of this biometric data
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this biometric data.
	 *
	 * @return the modified date of this biometric data
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this biometric data.
	 *
	 * @param modifiedDate the modified date of this biometric data
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the citizen ID of this biometric data.
	 *
	 * @return the citizen ID of this biometric data
	 */
	public long getCitizenId();

	/**
	 * Sets the citizen ID of this biometric data.
	 *
	 * @param citizenId the citizen ID of this biometric data
	 */
	public void setCitizenId(long citizenId);

	/**
	 * Returns the finger type of this biometric data.
	 *
	 * @return the finger type of this biometric data
	 */
	@AutoEscape
	public String getFingerType();

	/**
	 * Sets the finger type of this biometric data.
	 *
	 * @param fingerType the finger type of this biometric data
	 */
	public void setFingerType(String fingerType);

	/**
	 * Returns the finger print of this biometric data.
	 *
	 * @return the finger print of this biometric data
	 */
	public Blob getFingerPrint();

	/**
	 * Sets the finger print of this biometric data.
	 *
	 * @param fingerPrint the finger print of this biometric data
	 */
	public void setFingerPrint(Blob fingerPrint);

	/**
	 * Returns the remark of this biometric data.
	 *
	 * @return the remark of this biometric data
	 */
	@AutoEscape
	public String getRemark();

	/**
	 * Sets the remark of this biometric data.
	 *
	 * @param Remark the remark of this biometric data
	 */
	public void setRemark(String Remark);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		IdentificationDatabase.model.BiometricData biometricData);

	@Override
	public int hashCode();

	@Override
	public CacheModel<IdentificationDatabase.model.BiometricData> toCacheModel();

	@Override
	public IdentificationDatabase.model.BiometricData toEscapedModel();

	@Override
	public IdentificationDatabase.model.BiometricData toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}