/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package IdentificationDatabase.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CitizenRemark service. Represents a row in the &quot;ID_CitizenRemark&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link IdentificationDatabase.model.impl.CitizenRemarkModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link IdentificationDatabase.model.impl.CitizenRemarkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CitizenRemark
 * @see IdentificationDatabase.model.impl.CitizenRemarkImpl
 * @see IdentificationDatabase.model.impl.CitizenRemarkModelImpl
 * @generated
 */
@ProviderType
public interface CitizenRemarkModel extends AuditedModel,
	BaseModel<CitizenRemark>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a citizen remark model instance should use the {@link CitizenRemark} interface instead.
	 */

	/**
	 * Returns the primary key of this citizen remark.
	 *
	 * @return the primary key of this citizen remark
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this citizen remark.
	 *
	 * @param primaryKey the primary key of this citizen remark
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this citizen remark.
	 *
	 * @return the ID of this citizen remark
	 */
	public long getId();

	/**
	 * Sets the ID of this citizen remark.
	 *
	 * @param id the ID of this citizen remark
	 */
	public void setId(long id);

	/**
	 * Returns the company ID of this citizen remark.
	 *
	 * @return the company ID of this citizen remark
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this citizen remark.
	 *
	 * @param companyId the company ID of this citizen remark
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this citizen remark.
	 *
	 * @return the user ID of this citizen remark
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this citizen remark.
	 *
	 * @param userId the user ID of this citizen remark
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this citizen remark.
	 *
	 * @return the user uuid of this citizen remark
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this citizen remark.
	 *
	 * @param userUuid the user uuid of this citizen remark
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this citizen remark.
	 *
	 * @return the user name of this citizen remark
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this citizen remark.
	 *
	 * @param userName the user name of this citizen remark
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this citizen remark.
	 *
	 * @return the create date of this citizen remark
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this citizen remark.
	 *
	 * @param createDate the create date of this citizen remark
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this citizen remark.
	 *
	 * @return the modified date of this citizen remark
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this citizen remark.
	 *
	 * @param modifiedDate the modified date of this citizen remark
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the citizen ID of this citizen remark.
	 *
	 * @return the citizen ID of this citizen remark
	 */
	public long getCitizenId();

	/**
	 * Sets the citizen ID of this citizen remark.
	 *
	 * @param citizenId the citizen ID of this citizen remark
	 */
	public void setCitizenId(long citizenId);

	/**
	 * Returns the remark of this citizen remark.
	 *
	 * @return the remark of this citizen remark
	 */
	@AutoEscape
	public String getRemark();

	/**
	 * Sets the remark of this citizen remark.
	 *
	 * @param remark the remark of this citizen remark
	 */
	public void setRemark(String remark);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		IdentificationDatabase.model.CitizenRemark citizenRemark);

	@Override
	public int hashCode();

	@Override
	public CacheModel<IdentificationDatabase.model.CitizenRemark> toCacheModel();

	@Override
	public IdentificationDatabase.model.CitizenRemark toEscapedModel();

	@Override
	public IdentificationDatabase.model.CitizenRemark toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}