/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package IdentificationDatabase.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CitizenFingerprintMatcher service. Represents a row in the &quot;ID_CitizenFingerprintMatcher&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link IdentificationDatabase.model.impl.CitizenFingerprintMatcherModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link IdentificationDatabase.model.impl.CitizenFingerprintMatcherImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CitizenFingerprintMatcher
 * @see IdentificationDatabase.model.impl.CitizenFingerprintMatcherImpl
 * @see IdentificationDatabase.model.impl.CitizenFingerprintMatcherModelImpl
 * @generated
 */
@ProviderType
public interface CitizenFingerprintMatcherModel extends BaseModel<CitizenFingerprintMatcher> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a citizen fingerprint matcher model instance should use the {@link CitizenFingerprintMatcher} interface instead.
	 */

	/**
	 * Returns the primary key of this citizen fingerprint matcher.
	 *
	 * @return the primary key of this citizen fingerprint matcher
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this citizen fingerprint matcher.
	 *
	 * @param primaryKey the primary key of this citizen fingerprint matcher
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this citizen fingerprint matcher.
	 *
	 * @return the ID of this citizen fingerprint matcher
	 */
	public long getId();

	/**
	 * Sets the ID of this citizen fingerprint matcher.
	 *
	 * @param id the ID of this citizen fingerprint matcher
	 */
	public void setId(long id);

	/**
	 * Returns the create date of this citizen fingerprint matcher.
	 *
	 * @return the create date of this citizen fingerprint matcher
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this citizen fingerprint matcher.
	 *
	 * @param createDate the create date of this citizen fingerprint matcher
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this citizen fingerprint matcher.
	 *
	 * @return the modified date of this citizen fingerprint matcher
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this citizen fingerprint matcher.
	 *
	 * @param modifiedDate the modified date of this citizen fingerprint matcher
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the citizen ID of this citizen fingerprint matcher.
	 *
	 * @return the citizen ID of this citizen fingerprint matcher
	 */
	public long getCitizenId();

	/**
	 * Sets the citizen ID of this citizen fingerprint matcher.
	 *
	 * @param citizenId the citizen ID of this citizen fingerprint matcher
	 */
	public void setCitizenId(long citizenId);

	/**
	 * Returns the citizen ID second of this citizen fingerprint matcher.
	 *
	 * @return the citizen ID second of this citizen fingerprint matcher
	 */
	public long getCitizenIdSecond();

	/**
	 * Sets the citizen ID second of this citizen fingerprint matcher.
	 *
	 * @param citizenIdSecond the citizen ID second of this citizen fingerprint matcher
	 */
	public void setCitizenIdSecond(long citizenIdSecond);

	/**
	 * Returns the score of this citizen fingerprint matcher.
	 *
	 * @return the score of this citizen fingerprint matcher
	 */
	public int getScore();

	/**
	 * Sets the score of this citizen fingerprint matcher.
	 *
	 * @param score the score of this citizen fingerprint matcher
	 */
	public void setScore(int score);

	/**
	 * Returns the status of this citizen fingerprint matcher.
	 *
	 * @return the status of this citizen fingerprint matcher
	 */
	public int getStatus();

	/**
	 * Sets the status of this citizen fingerprint matcher.
	 *
	 * @param status the status of this citizen fingerprint matcher
	 */
	public void setStatus(int status);

	/**
	 * Returns the user ID of this citizen fingerprint matcher.
	 *
	 * @return the user ID of this citizen fingerprint matcher
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this citizen fingerprint matcher.
	 *
	 * @param userId the user ID of this citizen fingerprint matcher
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this citizen fingerprint matcher.
	 *
	 * @return the user uuid of this citizen fingerprint matcher
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this citizen fingerprint matcher.
	 *
	 * @param userUuid the user uuid of this citizen fingerprint matcher
	 */
	public void setUserUuid(String userUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		IdentificationDatabase.model.CitizenFingerprintMatcher citizenFingerprintMatcher);

	@Override
	public int hashCode();

	@Override
	public CacheModel<IdentificationDatabase.model.CitizenFingerprintMatcher> toCacheModel();

	@Override
	public IdentificationDatabase.model.CitizenFingerprintMatcher toEscapedModel();

	@Override
	public IdentificationDatabase.model.CitizenFingerprintMatcher toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}