/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package IdentificationDatabase.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Kebeles service. Represents a row in the &quot;ID_Kebeles&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link IdentificationDatabase.model.impl.KebelesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link IdentificationDatabase.model.impl.KebelesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Kebeles
 * @see IdentificationDatabase.model.impl.KebelesImpl
 * @see IdentificationDatabase.model.impl.KebelesModelImpl
 * @generated
 */
@ProviderType
public interface KebelesModel extends BaseModel<Kebeles>, GroupedModel,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a kebeles model instance should use the {@link Kebeles} interface instead.
	 */

	/**
	 * Returns the primary key of this kebeles.
	 *
	 * @return the primary key of this kebeles
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this kebeles.
	 *
	 * @param primaryKey the primary key of this kebeles
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this kebeles.
	 *
	 * @return the ID of this kebeles
	 */
	public long getId();

	/**
	 * Sets the ID of this kebeles.
	 *
	 * @param id the ID of this kebeles
	 */
	public void setId(long id);

	/**
	 * Returns the group ID of this kebeles.
	 *
	 * @return the group ID of this kebeles
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this kebeles.
	 *
	 * @param groupId the group ID of this kebeles
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this kebeles.
	 *
	 * @return the company ID of this kebeles
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this kebeles.
	 *
	 * @param companyId the company ID of this kebeles
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this kebeles.
	 *
	 * @return the user ID of this kebeles
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this kebeles.
	 *
	 * @param userId the user ID of this kebeles
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this kebeles.
	 *
	 * @return the user uuid of this kebeles
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this kebeles.
	 *
	 * @param userUuid the user uuid of this kebeles
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this kebeles.
	 *
	 * @return the user name of this kebeles
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this kebeles.
	 *
	 * @param userName the user name of this kebeles
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this kebeles.
	 *
	 * @return the create date of this kebeles
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this kebeles.
	 *
	 * @param createDate the create date of this kebeles
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this kebeles.
	 *
	 * @return the modified date of this kebeles
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this kebeles.
	 *
	 * @param modifiedDate the modified date of this kebeles
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the kebele or of this kebeles.
	 *
	 * @return the kebele or of this kebeles
	 */
	@AutoEscape
	public String getKebeleOr();

	/**
	 * Sets the kebele or of this kebeles.
	 *
	 * @param kebeleOr the kebele or of this kebeles
	 */
	public void setKebeleOr(String kebeleOr);

	/**
	 * Returns the kebele am of this kebeles.
	 *
	 * @return the kebele am of this kebeles
	 */
	@AutoEscape
	public String getKebeleAm();

	/**
	 * Sets the kebele am of this kebeles.
	 *
	 * @param kebeleAm the kebele am of this kebeles
	 */
	public void setKebeleAm(String kebeleAm);

	/**
	 * Returns the subcity or of this kebeles.
	 *
	 * @return the subcity or of this kebeles
	 */
	@AutoEscape
	public String getSubcityOr();

	/**
	 * Sets the subcity or of this kebeles.
	 *
	 * @param subcityOr the subcity or of this kebeles
	 */
	public void setSubcityOr(String subcityOr);

	/**
	 * Returns the subcity am of this kebeles.
	 *
	 * @return the subcity am of this kebeles
	 */
	@AutoEscape
	public String getSubcityAm();

	/**
	 * Sets the subcity am of this kebeles.
	 *
	 * @param subcityAm the subcity am of this kebeles
	 */
	public void setSubcityAm(String subcityAm);

	/**
	 * Returns the printername of this kebeles.
	 *
	 * @return the printername of this kebeles
	 */
	@AutoEscape
	public String getPrintername();

	/**
	 * Sets the printername of this kebeles.
	 *
	 * @param printername the printername of this kebeles
	 */
	public void setPrintername(String printername);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(IdentificationDatabase.model.Kebeles kebeles);

	@Override
	public int hashCode();

	@Override
	public CacheModel<IdentificationDatabase.model.Kebeles> toCacheModel();

	@Override
	public IdentificationDatabase.model.Kebeles toEscapedModel();

	@Override
	public IdentificationDatabase.model.Kebeles toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}