/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package IdentificationDatabase.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the RegistrationCitizen service. Represents a row in the &quot;ID_RegistrationCitizen&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link IdentificationDatabase.model.impl.RegistrationCitizenModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link IdentificationDatabase.model.impl.RegistrationCitizenImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RegistrationCitizen
 * @see IdentificationDatabase.model.impl.RegistrationCitizenImpl
 * @see IdentificationDatabase.model.impl.RegistrationCitizenModelImpl
 * @generated
 */
@ProviderType
public interface RegistrationCitizenModel extends BaseModel<RegistrationCitizen>,
	GroupedModel, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a registration citizen model instance should use the {@link RegistrationCitizen} interface instead.
	 */

	/**
	 * Returns the primary key of this registration citizen.
	 *
	 * @return the primary key of this registration citizen
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this registration citizen.
	 *
	 * @param primaryKey the primary key of this registration citizen
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this registration citizen.
	 *
	 * @return the ID of this registration citizen
	 */
	public long getId();

	/**
	 * Sets the ID of this registration citizen.
	 *
	 * @param id the ID of this registration citizen
	 */
	public void setId(long id);

	/**
	 * Returns the group ID of this registration citizen.
	 *
	 * @return the group ID of this registration citizen
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this registration citizen.
	 *
	 * @param groupId the group ID of this registration citizen
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this registration citizen.
	 *
	 * @return the company ID of this registration citizen
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this registration citizen.
	 *
	 * @param companyId the company ID of this registration citizen
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this registration citizen.
	 *
	 * @return the user ID of this registration citizen
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this registration citizen.
	 *
	 * @param userId the user ID of this registration citizen
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this registration citizen.
	 *
	 * @return the user uuid of this registration citizen
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this registration citizen.
	 *
	 * @param userUuid the user uuid of this registration citizen
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this registration citizen.
	 *
	 * @return the user name of this registration citizen
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this registration citizen.
	 *
	 * @param userName the user name of this registration citizen
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this registration citizen.
	 *
	 * @return the create date of this registration citizen
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this registration citizen.
	 *
	 * @param createDate the create date of this registration citizen
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this registration citizen.
	 *
	 * @return the modified date of this registration citizen
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this registration citizen.
	 *
	 * @param modifiedDate the modified date of this registration citizen
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the code of this registration citizen.
	 *
	 * @return the code of this registration citizen
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this registration citizen.
	 *
	 * @param code the code of this registration citizen
	 */
	public void setCode(String code);

	/**
	 * Returns the owner of this registration citizen.
	 *
	 * @return the owner of this registration citizen
	 */
	public boolean getOwner();

	/**
	 * Returns <code>true</code> if this registration citizen is owner.
	 *
	 * @return <code>true</code> if this registration citizen is owner; <code>false</code> otherwise
	 */
	public boolean isOwner();

	/**
	 * Sets whether this registration citizen is owner.
	 *
	 * @param owner the owner of this registration citizen
	 */
	public void setOwner(boolean owner);

	/**
	 * Returns the city of this registration citizen.
	 *
	 * @return the city of this registration citizen
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this registration citizen.
	 *
	 * @param city the city of this registration citizen
	 */
	public void setCity(String city);

	/**
	 * Returns the sub city of this registration citizen.
	 *
	 * @return the sub city of this registration citizen
	 */
	@AutoEscape
	public String getSubCity();

	/**
	 * Sets the sub city of this registration citizen.
	 *
	 * @param subCity the sub city of this registration citizen
	 */
	public void setSubCity(String subCity);

	/**
	 * Returns the kebele of this registration citizen.
	 *
	 * @return the kebele of this registration citizen
	 */
	@AutoEscape
	public String getKebele();

	/**
	 * Sets the kebele of this registration citizen.
	 *
	 * @param kebele the kebele of this registration citizen
	 */
	public void setKebele(String kebele);

	/**
	 * Returns the house no of this registration citizen.
	 *
	 * @return the house no of this registration citizen
	 */
	@AutoEscape
	public String getHouseNo();

	/**
	 * Sets the house no of this registration citizen.
	 *
	 * @param houseNo the house no of this registration citizen
	 */
	public void setHouseNo(String houseNo);

	/**
	 * Returns the name of this registration citizen.
	 *
	 * @return the name of this registration citizen
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this registration citizen.
	 *
	 * @param name the name of this registration citizen
	 */
	public void setName(String name);

	/**
	 * Returns the father name of this registration citizen.
	 *
	 * @return the father name of this registration citizen
	 */
	@AutoEscape
	public String getFatherName();

	/**
	 * Sets the father name of this registration citizen.
	 *
	 * @param fatherName the father name of this registration citizen
	 */
	public void setFatherName(String fatherName);

	/**
	 * Returns the grandfather name of this registration citizen.
	 *
	 * @return the grandfather name of this registration citizen
	 */
	@AutoEscape
	public String getGrandfatherName();

	/**
	 * Sets the grandfather name of this registration citizen.
	 *
	 * @param grandfatherName the grandfather name of this registration citizen
	 */
	public void setGrandfatherName(String grandfatherName);

	/**
	 * Returns the mother name of this registration citizen.
	 *
	 * @return the mother name of this registration citizen
	 */
	@AutoEscape
	public String getMotherName();

	/**
	 * Sets the mother name of this registration citizen.
	 *
	 * @param motherName the mother name of this registration citizen
	 */
	public void setMotherName(String motherName);

	/**
	 * Returns the citizenship of this registration citizen.
	 *
	 * @return the citizenship of this registration citizen
	 */
	@AutoEscape
	public String getCitizenship();

	/**
	 * Sets the citizenship of this registration citizen.
	 *
	 * @param citizenship the citizenship of this registration citizen
	 */
	public void setCitizenship(String citizenship);

	/**
	 * Returns the nation of this registration citizen.
	 *
	 * @return the nation of this registration citizen
	 */
	@AutoEscape
	public String getNation();

	/**
	 * Sets the nation of this registration citizen.
	 *
	 * @param nation the nation of this registration citizen
	 */
	public void setNation(String nation);

	/**
	 * Returns the birth date of this registration citizen.
	 *
	 * @return the birth date of this registration citizen
	 */
	public Date getBirthDate();

	/**
	 * Sets the birth date of this registration citizen.
	 *
	 * @param birthDate the birth date of this registration citizen
	 */
	public void setBirthDate(Date birthDate);

	/**
	 * Returns the birth place of this registration citizen.
	 *
	 * @return the birth place of this registration citizen
	 */
	@AutoEscape
	public String getBirthPlace();

	/**
	 * Sets the birth place of this registration citizen.
	 *
	 * @param birthPlace the birth place of this registration citizen
	 */
	public void setBirthPlace(String birthPlace);

	/**
	 * Returns the sex of this registration citizen.
	 *
	 * @return the sex of this registration citizen
	 */
	@AutoEscape
	public String getSex();

	/**
	 * Sets the sex of this registration citizen.
	 *
	 * @param sex the sex of this registration citizen
	 */
	public void setSex(String sex);

	/**
	 * Returns the occupation of this registration citizen.
	 *
	 * @return the occupation of this registration citizen
	 */
	@AutoEscape
	public String getOccupation();

	/**
	 * Sets the occupation of this registration citizen.
	 *
	 * @param occupation the occupation of this registration citizen
	 */
	public void setOccupation(String occupation);

	/**
	 * Returns the telephone of this registration citizen.
	 *
	 * @return the telephone of this registration citizen
	 */
	@AutoEscape
	public String getTelephone();

	/**
	 * Sets the telephone of this registration citizen.
	 *
	 * @param telephone the telephone of this registration citizen
	 */
	public void setTelephone(String telephone);

	/**
	 * Returns the relation of this registration citizen.
	 *
	 * @return the relation of this registration citizen
	 */
	@AutoEscape
	public String getRelation();

	/**
	 * Sets the relation of this registration citizen.
	 *
	 * @param relation the relation of this registration citizen
	 */
	public void setRelation(String relation);

	/**
	 * Returns the id type of this registration citizen.
	 *
	 * @return the id type of this registration citizen
	 */
	@AutoEscape
	public String getIdType();

	/**
	 * Sets the id type of this registration citizen.
	 *
	 * @param idType the id type of this registration citizen
	 */
	public void setIdType(String idType);

	/**
	 * Returns the issue date of this registration citizen.
	 *
	 * @return the issue date of this registration citizen
	 */
	public Date getIssueDate();

	/**
	 * Sets the issue date of this registration citizen.
	 *
	 * @param issueDate the issue date of this registration citizen
	 */
	public void setIssueDate(Date issueDate);

	/**
	 * Returns the expire date of this registration citizen.
	 *
	 * @return the expire date of this registration citizen
	 */
	public Date getExpireDate();

	/**
	 * Sets the expire date of this registration citizen.
	 *
	 * @param expireDate the expire date of this registration citizen
	 */
	public void setExpireDate(Date expireDate);

	/**
	 * Returns the emergency contact name of this registration citizen.
	 *
	 * @return the emergency contact name of this registration citizen
	 */
	@AutoEscape
	public String getEmergencyContactName();

	/**
	 * Sets the emergency contact name of this registration citizen.
	 *
	 * @param emergencyContactName the emergency contact name of this registration citizen
	 */
	public void setEmergencyContactName(String emergencyContactName);

	/**
	 * Returns the emergency contac phone of this registration citizen.
	 *
	 * @return the emergency contac phone of this registration citizen
	 */
	@AutoEscape
	public String getEmergencyContacPhone();

	/**
	 * Sets the emergency contac phone of this registration citizen.
	 *
	 * @param emergencyContacPhone the emergency contac phone of this registration citizen
	 */
	public void setEmergencyContacPhone(String emergencyContacPhone);

	/**
	 * Returns the image of this registration citizen.
	 *
	 * @return the image of this registration citizen
	 */
	@AutoEscape
	public String getImage();

	/**
	 * Sets the image of this registration citizen.
	 *
	 * @param image the image of this registration citizen
	 */
	public void setImage(String image);

	/**
	 * Returns the signature of this registration citizen.
	 *
	 * @return the signature of this registration citizen
	 */
	@AutoEscape
	public String getSignature();

	/**
	 * Sets the signature of this registration citizen.
	 *
	 * @param signature the signature of this registration citizen
	 */
	public void setSignature(String signature);

	/**
	 * Returns the fingerprint of this registration citizen.
	 *
	 * @return the fingerprint of this registration citizen
	 */
	@AutoEscape
	public String getFingerprint();

	/**
	 * Sets the fingerprint of this registration citizen.
	 *
	 * @param fingerprint the fingerprint of this registration citizen
	 */
	public void setFingerprint(String fingerprint);

	/**
	 * Returns the status of this registration citizen.
	 *
	 * @return the status of this registration citizen
	 */
	public int getStatus();

	/**
	 * Sets the status of this registration citizen.
	 *
	 * @param status the status of this registration citizen
	 */
	public void setStatus(int status);

	/**
	 * Returns the recipt no of this registration citizen.
	 *
	 * @return the recipt no of this registration citizen
	 */
	@AutoEscape
	public String getReciptNo();

	/**
	 * Sets the recipt no of this registration citizen.
	 *
	 * @param reciptNo the recipt no of this registration citizen
	 */
	public void setReciptNo(String reciptNo);

	/**
	 * Returns the notice of this registration citizen.
	 *
	 * @return the notice of this registration citizen
	 */
	@AutoEscape
	public String getNotice();

	/**
	 * Sets the notice of this registration citizen.
	 *
	 * @param notice the notice of this registration citizen
	 */
	public void setNotice(String notice);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		IdentificationDatabase.model.RegistrationCitizen registrationCitizen);

	@Override
	public int hashCode();

	@Override
	public CacheModel<IdentificationDatabase.model.RegistrationCitizen> toCacheModel();

	@Override
	public IdentificationDatabase.model.RegistrationCitizen toEscapedModel();

	@Override
	public IdentificationDatabase.model.RegistrationCitizen toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}