/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package IdentificationDatabase.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Services service. Represents a row in the &quot;ID_Services&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link IdentificationDatabase.model.impl.ServicesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link IdentificationDatabase.model.impl.ServicesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Services
 * @see IdentificationDatabase.model.impl.ServicesImpl
 * @see IdentificationDatabase.model.impl.ServicesModelImpl
 * @generated
 */
@ProviderType
public interface ServicesModel extends BaseModel<Services>, GroupedModel,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a services model instance should use the {@link Services} interface instead.
	 */

	/**
	 * Returns the primary key of this services.
	 *
	 * @return the primary key of this services
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this services.
	 *
	 * @param primaryKey the primary key of this services
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this services.
	 *
	 * @return the ID of this services
	 */
	public long getId();

	/**
	 * Sets the ID of this services.
	 *
	 * @param id the ID of this services
	 */
	public void setId(long id);

	/**
	 * Returns the group ID of this services.
	 *
	 * @return the group ID of this services
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this services.
	 *
	 * @param groupId the group ID of this services
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this services.
	 *
	 * @return the company ID of this services
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this services.
	 *
	 * @param companyId the company ID of this services
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this services.
	 *
	 * @return the user ID of this services
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this services.
	 *
	 * @param userId the user ID of this services
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this services.
	 *
	 * @return the user uuid of this services
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this services.
	 *
	 * @param userUuid the user uuid of this services
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this services.
	 *
	 * @return the user name of this services
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this services.
	 *
	 * @param userName the user name of this services
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this services.
	 *
	 * @return the create date of this services
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this services.
	 *
	 * @param createDate the create date of this services
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this services.
	 *
	 * @return the modified date of this services
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this services.
	 *
	 * @param modifiedDate the modified date of this services
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the citizen ID of this services.
	 *
	 * @return the citizen ID of this services
	 */
	public long getCitizenId();

	/**
	 * Sets the citizen ID of this services.
	 *
	 * @param citizenId the citizen ID of this services
	 */
	public void setCitizenId(long citizenId);

	/**
	 * Returns the service of this services.
	 *
	 * @return the service of this services
	 */
	@AutoEscape
	public String getService();

	/**
	 * Sets the service of this services.
	 *
	 * @param service the service of this services
	 */
	public void setService(String service);

	/**
	 * Returns the status of this services.
	 *
	 * @return the status of this services
	 */
	public int getStatus();

	/**
	 * Sets the status of this services.
	 *
	 * @param status the status of this services
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(IdentificationDatabase.model.Services services);

	@Override
	public int hashCode();

	@Override
	public CacheModel<IdentificationDatabase.model.Services> toCacheModel();

	@Override
	public IdentificationDatabase.model.Services toEscapedModel();

	@Override
	public IdentificationDatabase.model.Services toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}