/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package IdentificationDatabase.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Settings service. Represents a row in the &quot;ID_Settings&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link IdentificationDatabase.model.impl.SettingsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link IdentificationDatabase.model.impl.SettingsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Settings
 * @see IdentificationDatabase.model.impl.SettingsImpl
 * @see IdentificationDatabase.model.impl.SettingsModelImpl
 * @generated
 */
@ProviderType
public interface SettingsModel extends BaseModel<Settings>, GroupedModel,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a settings model instance should use the {@link Settings} interface instead.
	 */

	/**
	 * Returns the primary key of this settings.
	 *
	 * @return the primary key of this settings
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this settings.
	 *
	 * @param primaryKey the primary key of this settings
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this settings.
	 *
	 * @return the ID of this settings
	 */
	public long getId();

	/**
	 * Sets the ID of this settings.
	 *
	 * @param id the ID of this settings
	 */
	public void setId(long id);

	/**
	 * Returns the group ID of this settings.
	 *
	 * @return the group ID of this settings
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this settings.
	 *
	 * @param groupId the group ID of this settings
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this settings.
	 *
	 * @return the company ID of this settings
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this settings.
	 *
	 * @param companyId the company ID of this settings
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this settings.
	 *
	 * @return the user ID of this settings
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this settings.
	 *
	 * @param userId the user ID of this settings
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this settings.
	 *
	 * @return the user uuid of this settings
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this settings.
	 *
	 * @param userUuid the user uuid of this settings
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this settings.
	 *
	 * @return the user name of this settings
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this settings.
	 *
	 * @param userName the user name of this settings
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this settings.
	 *
	 * @return the create date of this settings
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this settings.
	 *
	 * @param createDate the create date of this settings
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this settings.
	 *
	 * @return the modified date of this settings
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this settings.
	 *
	 * @param modifiedDate the modified date of this settings
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the assigned user ID of this settings.
	 *
	 * @return the assigned user ID of this settings
	 */
	public long getAssignedUserId();

	/**
	 * Sets the assigned user ID of this settings.
	 *
	 * @param assignedUserId the assigned user ID of this settings
	 */
	public void setAssignedUserId(long assignedUserId);

	/**
	 * Returns the assigned user uuid of this settings.
	 *
	 * @return the assigned user uuid of this settings
	 */
	public String getAssignedUserUuid();

	/**
	 * Sets the assigned user uuid of this settings.
	 *
	 * @param assignedUserUuid the assigned user uuid of this settings
	 */
	public void setAssignedUserUuid(String assignedUserUuid);

	/**
	 * Returns the organization ID of this settings.
	 *
	 * @return the organization ID of this settings
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this settings.
	 *
	 * @param organizationId the organization ID of this settings
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the role ID of this settings.
	 *
	 * @return the role ID of this settings
	 */
	public long getRoleId();

	/**
	 * Sets the role ID of this settings.
	 *
	 * @param roleId the role ID of this settings
	 */
	public void setRoleId(long roleId);

	/**
	 * Returns the remark of this settings.
	 *
	 * @return the remark of this settings
	 */
	@AutoEscape
	public String getRemark();

	/**
	 * Sets the remark of this settings.
	 *
	 * @param remark the remark of this settings
	 */
	public void setRemark(String remark);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(IdentificationDatabase.model.Settings settings);

	@Override
	public int hashCode();

	@Override
	public CacheModel<IdentificationDatabase.model.Settings> toCacheModel();

	@Override
	public IdentificationDatabase.model.Settings toEscapedModel();

	@Override
	public IdentificationDatabase.model.Settings toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}